In [ ]:
https://raw.githubusercontent.com/BryanJimenezUtec/etl-data-pipeline/refs/heads/main/data/raw/siniestros.csv

In [2]:
import pandas as pd

In [3]:
url ="https://raw.githubusercontent.com/BryanJimenezUtec/etl-data-pipeline/refs/heads/main/data/raw/siniestros.csv"
df = pd.read_csv(url)
df.head()

   id_siniestro  id_poliza fecha_siniestro monto_siniestro     estado
0             1      17400      16-10-2025         2092.59    ABIERTO
1             2       2465      01/08/2025        7,076.25    Abierto
2             3      15785      19-09-2025         702.27     cerrado
3             4      14299      27/09/2025         274.63     Abierto
4             5      12908      01/12/2025        9,377.69  Rechazado

In [ ]:
import pandas as pd

In [4]:
#Exploración de datos
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4620 entries, 0 to 4619
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_siniestro     4620 non-null   int64
 1   id_poliza        4620 non-null   int64
 2   fecha_siniestro  4620 non-null   object
 3   monto_siniestro  4004 non-null   object
 4   estado           3322 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.6+ KB

id_siniestro          0
id_poliza             0
fecha_siniestro       0
monto_siniestro     616
estado             1298
dtype: int64

LIMPIEZA DE DATOS

In [6]:
# 1. Copia y normalización de columnas
siniestros = df.copy()
siniestros.columns = siniestros.columns.str.strip().str.lower()

# 2. LIMPIEZA DE FECHAS
siniestros['fecha_siniestro'] = pd.to_datetime(siniestros['fecha_siniestro'], dayfirst=True, errors='coerce')

# 3. LIMPIEZA DE MONTOS
siniestros['monto_siniestro'] = siniestros['monto_siniestro'].astype(str).str.replace(',', '', regex=False)
siniestros['monto_siniestro'] = pd.to_numeric(siniestros['monto_siniestro'], errors='coerce')

# 4. FORMATEAR ESTADO
siniestros['estado'] = siniestros['estado'].astype(str).str.strip().str.capitalize()

# D. Limpieza adicional
for col in siniestros.select_dtypes(include='object').columns:
    siniestros[col] = siniestros[col].replace(r'^\s*$', pd.NA, regex=True)

In [7]:
# Separar datos válidos y rechazados para Siniestros

validos_sin = siniestros[
    siniestros['id_siniestro'].notna() &
    siniestros['fecha_siniestro'].notna() &
    siniestros['monto_siniestro'].notna()
].copy()

rechazados_sin = siniestros[
    siniestros['id_siniestro'].isna() |
    siniestros['fecha_siniestro'].isna() |
    siniestros['monto_siniestro'].isna()
].copy()


print(f"Registros válidos de siniestros: {len(validos_sin)}")
print(f"Registros rechazados de siniestros: {len(rechazados_sin)}")

Registros válidos de siniestros: 739
Registros rechazados de siniestros: 3881

In [8]:
# Motivo de rechazo para Siniestros
def motivo_siniestro(row):
    motivos = []

    # Validar si falta el ID del siniestro
    if pd.isna(row['id_siniestro']):
        motivos.append("id_vacio")

    # Validar si la fecha es inválida o nula
    if pd.isna(row['fecha_siniestro']):
        motivos.append("fecha_error")

    # Validar si el monto es inválido o nulo
    if pd.isna(row['monto_siniestro']):
        motivos.append("monto_error")

    return ",".join(motivos)

# Aplicar la función al DataFrame de rechazados de siniestros
rechazados_sin["motivo_rechazo"] = rechazados_sin.apply(motivo_siniestro, axis=1)

In [9]:
# Exportar archivos
validos_sin.to_csv("siniestros_curated.csv", index=False)
rechazados_sin.to_csv("siniestros_rejects.csv", index=False)

print("Archivos 'siniestros_curated.csv' y 'siniestros_rejects.csv' generados con éxito.")

Archivos 'siniestros_curated.csv' y 'siniestros_rejects.csv' generados con éxito.

Conectar BD a render

In [10]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 42.0 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [11]:
from sqlalchemy import create_engine
import pandas as pd

In [12]:
database_url = "postgresql://etl_user:KWIr9XJ0F6G6c8YE7pj9J9RzFgRA6wo5@dpg-d6qu5nlm5p6s73ea88hg-a.oregon-postgres.render.com/etl_seguros_ibd2"

In [13]:
engine = create_engine(database_url)

In [14]:
test = pd.read_sql("SELECT 1", engine)

In [15]:
# 1. Cargar siniestros válidos
validos_sin.to_sql(
    'siniestros_curated',
    engine,
    if_exists='replace',
    index=False
)

# 2. Cargar siniestros rechazados
rechazados_sin.to_sql(
    'siniestros_rejects',
    engine,
    if_exists='replace',
    index=False
)

print("Carga de Siniestros a PostgreSQL completada exitosamente.")

Carga de Siniestros a PostgreSQL completada exitosamente.

In [16]:
# Validar la carga de Siniestros en PostgreSQL
pd.read_sql(
    "SELECT * FROM siniestros_curated LIMIT 10",
    engine
)

   id_siniestro  id_poliza fecha_siniestro  monto_siniestro     estado
0             1      17400      2025-10-16          2092.59    Abierto
1             3      15785      2025-09-19           702.27    Cerrado
2             8      23824      2025-01-17          2736.20    Abierto
3            13       3716      2025-07-13         -4274.39  Rechazado
4            24      17180      2025-06-13          6183.83    Cerrado
5            27      22625      2025-03-07           141.77        Nan
6            33       2231      2025-09-21          2443.90  Rechazado
7            36      16929      2025-01-06          3649.94    Cerrado
8            45      15100      2025-01-27          8761.24    Abierto
9            66      14064      2025-03-25          9842.05    Abierto